#!/bin/bash

# Convert a full folder of L1TNtuple files to h5s.
# Calls the produce_h5 script within the same folder.

# Read folder path given by user.
while [ $# -gt 0 ]; do
  case "$1" in
    --folder*|-f*)
      if [[ "$1" != *=* ]]; then shift; fi
      FOLDER="${1#*=}"
      ;;
    --prescale*|-p*)
      if [[ "$1" != *=* ]]; then shift; fi
      PRESCALE="${1#*=}"
      ;;
    --output*|-o*)
      if [[ "$1" != *=* ]]; then shift; fi
      OUTPUT="${1#*=}"
      ;;
    --mc|-m)
      mc=true
      ;;
    --njobs*|-j*)
      if [[ "$1" != *=* ]]; then shift; fi
      NJOBS="${1#*=}"
      ;;
    --help|-h)
      printf "Script that converts a given folder of L1TNtuples to h5 files.\n" \
             "Usage: ./convert_folder.sh\n\n" \
             "--folder -f : Path to the folder to convert.\n" \
             "--prescale -p : Path to the prescale file to use.\n" \
             "--output -o : Path to the output folder.\n" \
             "--mc -m : Flag whether the folder to convert is gen by MC.\n" \
             "--njobs -j : Number of jobs to run at the same time.\n"
      exit 0
      ;;
    *)
      >&2 printf "Error: Invalid arguments! Use --help to learn how to use this script.\n"
      exit 1
      ;;
  esac
  shift
done

mkdir -p ${OUTPUT}
mkdir -p ${OUTPUT}/logs

if [[ -z ${mc} ]];then
    mc=false
fi

for file in ${FOLDER}/*.root; do
    [ -f "${file}" ] || break

    # Get name of the file without extensions.
    filename=${file##*/}
    filename=${filename%%.*}

    # Produce h5 given the input file is generated by Monte Carlo simulation.
    if [ "$mc" = true ] ; then
        ./produce_h5 --input_file ${file} --prescale_file ${PRESCALE} --output_path ${OUTPUT} --mc > ${OUTPUT}/logs/${filename}.out 2>&1 &
    fi

    # Produce h5 given the input file is Zero Bias data.
    if [ "$mc" = false ] ; then
        ./produce_h5 --input_file ${file} --prescale_file ${PRESCALE} --output_path ${OUTPUT} > ${OUTPUT}/logs/${filename}.out 2>&1 &
    fi

    # Check how many background jobs there are.
    background=( $(jobs -p) )
    if (( ${#background[@]} == ${NJOBS} )); then
        wait -n
    fi
done
