#!/usr/bin/env python

# Merges the data given a folder.
import argparse
from pathlib import Path

import h5py
import numpy as np

from l1trigger_datamaker.h5convert import root2h5


parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('--folder', type=str, help="Path to the folder with the h5s.")
args = parser.parse_args()

folder = Path(args.folder)
reader = root2h5.Root2h5()
reader.read_folder(folder)
reader.close_h5()
