#!/usr/bin/env python

# Plots the data given a folder of h5 files.
import argparse
from pathlib import Path

import h5py
import numpy as np

from l1trigger_datamaker.h5convert import root2h5
from l1trigger_datamaker.h5convert import plots
from l1trigger_datamaker.h5convert.terminal_colors import tcols


parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('--folder', type=str, help="Path to the folder with the h5s.")
args = parser.parse_args()

folder = Path(args.folder)
reader = root2h5.Root2h5()
# h5file = reader.read_folder(folder)
df = reader.read_folder_pandas(folder)

exit(1)

print(tcols.OKGREEN + "\nPlotting the particle objects..." + tcols.ENDC)
for obj in reader.particles.keys():
    plots.plot_hist_3d(h5file[obj], obj, reader.particles[obj], folder)

print(tcols.OKGREEN + "\nPlotting the energy objects...\n" + tcols.ENDC)
for obj in reader.energies.keys():
    plots.plot_hist_2d(h5file[obj], obj, reader.energies[obj], folder)

print(tcols.OKGREEN + "\nPlotting the cicada objects...\n" + tcols.ENDC)
for obj in reader.cicada.keys():
    plots.plot_hist_1d(h5file[obj], reader.cicada[obj], folder)

h5file.close()
