#!/usr/bin/env python

# Run the conversion script from L1TNtuple to h5.
import argparse

from L1Trigger_data.h5convert import root2h5

parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('--input_file', type=str, help="Path to root file for converison.")
parser.add_argument('--mc', action='store_true', help="Whether file is MC or not.")
parser.add_argument('--prescale_file', type=str, help="Path to prescale file.")
parser.add_argument('--output_path', type=str, help="Path to folder containing output.")

parser.add_argument('--l1_tree_name', type=str, default='l1UpgradeEmuTree/L1UpgradeTree',
    help="The name of the level 1 trigger tree to convert in the root input file.")
parser.add_argument('--uGT_tree_name', type=str, default='l1uGTEmuTree/L1uGTTree',
    help="The name of the global trigger tree inside the l1 trigger tree. ")
parser.add_argument('--event_tree_name', type=str, default='l1EventTree/L1EventTree',
    help="The name of the event tree in the global trigger tree.")
parser.add_argument('--calosumm_tree_name', type=str,
    default='l1CaloSummaryEmuTree/L1CaloSummaryTree',
    help="The name of the calorimeter data summary tree that contains the cicada bits.")
parser.add_argument('--gen_tree_name', type=str, default='l1GeneratorTree/L1GenTree',
    help="The name of the tree with mc generator information for additional studies.")
args = parser.parse_args()


root2h5.Root2h5().convert(**vars(args))
