#!/usr/bin/env python

# Run the conversion script from L1TNtuple to h5.
import hydra
from omegaconf import DictConfig, OmegaConf

from adl1t_datamaker import root2parquet
from adl1t_datamaker import util


@hydra.main(version_base=None, config_path="configs", config_name="convert.yaml")
def main(cfg: DictConfig) -> None:
    util.print_config(cfg, resolve=True)

    converter = root2parquet.Root2Parquet(**cfg["converter"])
    for input_folder, output_folder in cfg["paths"]["input_output_folders"].items():
        input_folder_path = cfg["paths"]["input_root_path"] + f"/{input_folder}"
        output_folder_path = cfg["output_root_path"] + f"/{output_folder}"

        converter.convert_folder(
            folder=input_folder_path,
            output_path=output_folder_path,
            **cfg["paths"]["auxiliary_files"],
            ncores=cfg["ncores"],
        )

if __name__ == "__main__":
    main()
